apiVersion: v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-deploy
  template:  
    metadata:
      name: voting-app-deploy
      labels:
        name: voting-app-deploy
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
    
